name: tagpr

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  tagpr:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: Songmu/tagpr@d1b8138b7a31075141b6cd64103de9485ced7ac9 # v1.20.1
